# Generated by Django 5.2.15 on 2026-06-06 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_name", models.CharField(default="ObsoleteHQ", max_length=120)),
                ("domain", models.CharField(default="obsoletehq.com", max_length=160)),
                (
                    "homepage_primary_cta",
                    models.CharField(default="Start Learning", max_length=80),
                ),
                ("setup_completed", models.BooleanField(default=False)),
                ("maintenance_mode", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Site settings",
                "verbose_name_plural": "Site settings",
            },
        ),
    ]
