# Generated by Django 5.2.15 on 2026-06-06 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("learning", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DebugCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("slug", models.SlugField(unique=True)),
                ("symptom", models.CharField(max_length=220)),
                ("what_it_usually_means", models.TextField()),
                ("first_checks", models.TextField()),
                ("fixes", models.TextField()),
                ("safety_warning", models.TextField(blank=True)),
                ("published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "related_learning_experiences",
                    models.ManyToManyField(
                        blank=True,
                        related_name="debug_cards",
                        to="learning.learningexperience",
                    ),
                ),
            ],
            options={
                "ordering": ("title",),
            },
        ),
    ]
