# Generated by Django 5.2.15 on 2026-06-06 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Kit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                ("source_vendor", models.CharField(blank=True, max_length=120)),
                ("url", models.URLField(blank=True)),
                ("recommended", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("image", models.ImageField(blank=True, upload_to="kits/")),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="SafetyWarning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("slug", models.SlugField(unique=True)),
                ("body", models.TextField()),
                ("severity", models.CharField(default="Low", max_length=40)),
                ("published", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("severity", "title"),
            },
        ),
        migrations.CreateModel(
            name="Track",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveSmallIntegerField(unique=True)),
                ("title", models.CharField(max_length=160)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("published", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("order", "number"),
            },
        ),
        migrations.CreateModel(
            name="Component",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "signal_type",
                    models.CharField(
                        choices=[
                            ("digital", "Digital"),
                            ("analog", "Analog"),
                            ("pwm", "PWM"),
                            ("i2c", "I2C"),
                            ("spi", "SPI"),
                            ("uart", "UART"),
                            ("one_wire", "One-wire"),
                            ("power", "Power output"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=24,
                    ),
                ),
                ("power_requirement", models.CharField(blank=True, max_length=160)),
                ("pins", models.CharField(blank=True, max_length=180)),
                ("voltage_notes", models.TextField(blank=True)),
                ("safety_notes", models.TextField(blank=True)),
                ("common_mistakes", models.TextField(blank=True)),
                ("image", models.ImageField(blank=True, upload_to="components/")),
                (
                    "kits",
                    models.ManyToManyField(
                        blank=True, related_name="components", to="learning.kit"
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="LearningExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=12, unique=True)),
                ("title", models.CharField(max_length=180)),
                ("slug", models.SlugField(unique=True)),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("concept", "Concept Lesson"),
                            ("skill_lab", "Skill Lab"),
                            ("guided_build", "Guided Build"),
                            ("project", "Project Tutorial"),
                            ("capstone", "Capstone Sprint"),
                            ("reference", "Reference / Debug Card"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("builder", "Builder"),
                            ("explorer", "Explorer"),
                            ("inventor", "Inventor"),
                            ("advanced", "Advanced"),
                        ],
                        default="beginner",
                        max_length=24,
                    ),
                ),
                ("estimated_time", models.CharField(blank=True, max_length=80)),
                ("main_skill", models.CharField(blank=True, max_length=160)),
                ("prerequisites", models.TextField(blank=True)),
                ("summary", models.TextField(blank=True)),
                ("hook", models.CharField(blank=True, max_length=220)),
                ("student_outcome", models.TextField(blank=True)),
                (
                    "safety_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("supervised", "Supervised"),
                        ],
                        default="low",
                        max_length=24,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("review", "Review"),
                            ("published", "Published"),
                            ("hidden", "Hidden"),
                            ("retired", "Retired"),
                        ],
                        default="draft",
                        max_length=24,
                    ),
                ),
                (
                    "core_run_week",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("core_anchor", models.BooleanField(default=False)),
                ("a_la_carte", models.BooleanField(default=True)),
                ("optional_bonus", models.BooleanField(default=False)),
                ("recommended_after_core", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "required_components",
                    models.ManyToManyField(
                        blank=True,
                        related_name="learning_experiences",
                        to="learning.component",
                    ),
                ),
                (
                    "required_kits",
                    models.ManyToManyField(
                        blank=True,
                        related_name="learning_experiences",
                        to="learning.kit",
                    ),
                ),
                (
                    "safety_warnings",
                    models.ManyToManyField(
                        blank=True,
                        related_name="learning_experiences",
                        to="learning.safetywarning",
                    ),
                ),
                (
                    "track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="learning_experiences",
                        to="learning.track",
                    ),
                ),
            ],
            options={
                "ordering": ("track__number", "code"),
            },
        ),
        migrations.CreateModel(
            name="CoreRunWeek",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_number", models.PositiveSmallIntegerField(unique=True)),
                ("title", models.CharField(max_length=160)),
                ("theme", models.CharField(blank=True, max_length=160)),
                ("goal", models.TextField(blank=True)),
                ("summary", models.TextField(blank=True)),
                ("estimated_time", models.CharField(blank=True, max_length=80)),
                ("published", models.BooleanField(default=True)),
                (
                    "anchor_learning_experiences",
                    models.ManyToManyField(
                        blank=True,
                        related_name="core_anchor_weeks",
                        to="learning.learningexperience",
                    ),
                ),
                (
                    "optional_bonus_learning_experiences",
                    models.ManyToManyField(
                        blank=True,
                        related_name="core_bonus_weeks",
                        to="learning.learningexperience",
                    ),
                ),
                (
                    "track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="core_run_weeks",
                        to="learning.track",
                    ),
                ),
            ],
            options={
                "ordering": ("week_number",),
            },
        ),
        migrations.CreateModel(
            name="LearningExperienceSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("parts", "Parts"),
                            ("wiring", "Wiring"),
                            ("code", "Code placeholder"),
                            ("checkpoint", "Checkpoint"),
                            ("debug", "Debug"),
                            ("remix", "Remix"),
                            ("reflection", "Reflection"),
                            ("safety", "Safety"),
                            ("media", "Media"),
                        ],
                        default="text",
                        max_length=24,
                    ),
                ),
                ("body", models.TextField(blank=True)),
                ("media", models.FileField(blank=True, upload_to="learning/")),
                ("published", models.BooleanField(default=True)),
                (
                    "learning_experience",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="learning.learningexperience",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
                "unique_together": {("learning_experience", "order")},
            },
        ),
    ]
