# Generated by Codex on 2026-06-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="learningexperiencesection",
            name="static_asset_alt",
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name="learningexperiencesection",
            name="static_asset_caption",
            field=models.CharField(blank=True, max_length=260),
        ),
        migrations.AddField(
            model_name="learningexperiencesection",
            name="static_asset_path",
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name="learningexperiencesection",
            name="static_asset_source_name",
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name="learningexperiencesection",
            name="static_asset_source_url",
            field=models.URLField(blank=True),
        ),
    ]
