# Generated by Django 5.2.15 on 2026-06-07 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0002_learningexperiencesection_static_assets"),
    ]

    operations = [
        migrations.AddField(
            model_name="component",
            name="attribution",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="component",
            name="category",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="component",
            name="datasheet_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="component",
            name="discrete_parts",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="component",
            name="how_it_is_used",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="component",
            name="libraries",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="component",
            name="main_component",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="component",
            name="pinout_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="component",
            name="source_name",
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name="component",
            name="source_url",
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name="ComponentAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("static_asset_path", models.CharField(max_length=240)),
                ("alt_text", models.CharField(max_length=220)),
                ("caption", models.CharField(blank=True, max_length=260)),
                ("source_name", models.CharField(blank=True, max_length=180)),
                ("source_url", models.URLField(blank=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="learning.component",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
            },
        ),
        migrations.CreateModel(
            name="ComponentResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("url", models.URLField()),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("sunfounder", "SunFounder source"),
                            ("datasheet", "Datasheet"),
                            ("guide", "Reference guide"),
                            ("library", "Library / driver"),
                            ("other", "Other useful link"),
                        ],
                        default="other",
                        max_length=24,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="learning.component",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "title"),
            },
        ),
    ]
