# Generated by Django 5.2.15 on 2026-06-07 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0003_component_attribution_component_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="component",
            name="pins",
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AlterField(
            model_name="component",
            name="power_requirement",
            field=models.CharField(blank=True, max_length=240),
        ),
    ]
