# Generated by Django 5.2.15 on 2026-06-06 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(default="spark", max_length=40)),
                ("reward_xp", models.PositiveIntegerField(default=0)),
                ("criteria_type", models.CharField(blank=True, max_length=80)),
                ("published", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
    ]
